### ISSUE TITLE
Backport to 1.19.2

### ISSUE THREAD

**Issue by suerion** [BananaPuppy/MoreFuel#1]
**Describe the solution you'd like**
It would be nice, if you could Backport this to 1.19.2, because we had some Mods on 1.19.2 but they need time to update to 1.20.x

Thanks a lot

**Comment by suerion** [comment]
Could you also add this feature in the mod?

https://modrinth.com/mod/fuelgoeshere

**Comment by BananaPuppy** [comment]
@suerion 
https://modrinth.com/mod/more-fuel/version/huFPZDYi
I didn't test this super rigorously
if you have any problems, feel free to message my on discord: bananapuppy

**Comment by suerion** [comment]
Thanks a lot, i will come to you, if there is a problem :)
